
package com.bercut.wsdl.ServiceControl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BusinessException", targetNamespace = "http://www.bercut.com/schema/ServiceControl")
public class CheckAbilityFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CheckAbilityFault(String message, BusinessFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CheckAbilityFault(String message, BusinessFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bercut.wsdl.ServiceControl.BusinessFault
     */
    public BusinessFault getFaultInfo() {
        return faultInfo;
    }

}
