
package com.bercut.wsdl.ServiceControl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceControlService", targetNamespace = "http://www.bercut.com/wsdl/ServiceControl", wsdlLocation = "file:/C:/dev/ws/ws/ServiceControl/ServiceControl.wsdl")
public class ServiceControlService
    extends Service
{

    private final static URL SERVICECONTROLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICECONTROLSERVICE_EXCEPTION;
    private final static QName SERVICECONTROLSERVICE_QNAME = new QName("http://www.bercut.com/wsdl/ServiceControl", "ServiceControlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/dev/ws/ws/ServiceControl/ServiceControl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICECONTROLSERVICE_WSDL_LOCATION = url;
        SERVICECONTROLSERVICE_EXCEPTION = e;
    }

    public ServiceControlService() {
        super(__getWsdlLocation(), SERVICECONTROLSERVICE_QNAME);
    }

    public ServiceControlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICECONTROLSERVICE_QNAME, features);
    }

    public ServiceControlService(URL wsdlLocation) {
        super(wsdlLocation, SERVICECONTROLSERVICE_QNAME);
    }

    public ServiceControlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICECONTROLSERVICE_QNAME, features);
    }

    public ServiceControlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceControlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceControlPortType
     */
    @WebEndpoint(name = "ServiceControlPort")
    public ServiceControlPortType getServiceControlPort() {
        return super.getPort(new QName("http://www.bercut.com/wsdl/ServiceControl", "ServiceControlPort"), ServiceControlPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceControlPortType
     */
    @WebEndpoint(name = "ServiceControlPort")
    public ServiceControlPortType getServiceControlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bercut.com/wsdl/ServiceControl", "ServiceControlPort"), ServiceControlPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICECONTROLSERVICE_EXCEPTION!= null) {
            throw SERVICECONTROLSERVICE_EXCEPTION;
        }
        return SERVICECONTROLSERVICE_WSDL_LOCATION;
    }

}
