
package com.bercut.specs.aoi.tele2.subscribercontrolbpel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubscriberControlService", targetNamespace = "http://www.bercut.com/specs/aoi/tele2/SubscriberControlBpel", wsdlLocation = "file:/C:/dev/ws/ws/SubscriberControl/SubscriberControl.wsdl")
public class SubscriberControlService
    extends Service
{

    private final static URL SUBSCRIBERCONTROLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUBSCRIBERCONTROLSERVICE_EXCEPTION;
    private final static QName SUBSCRIBERCONTROLSERVICE_QNAME = new QName("http://www.bercut.com/specs/aoi/tele2/SubscriberControlBpel", "SubscriberControlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/dev/ws/ws/SubscriberControl/SubscriberControl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUBSCRIBERCONTROLSERVICE_WSDL_LOCATION = url;
        SUBSCRIBERCONTROLSERVICE_EXCEPTION = e;
    }

    public SubscriberControlService() {
        super(__getWsdlLocation(), SUBSCRIBERCONTROLSERVICE_QNAME);
    }

    public SubscriberControlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBSCRIBERCONTROLSERVICE_QNAME, features);
    }

    public SubscriberControlService(URL wsdlLocation) {
        super(wsdlLocation, SUBSCRIBERCONTROLSERVICE_QNAME);
    }

    public SubscriberControlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBSCRIBERCONTROLSERVICE_QNAME, features);
    }

    public SubscriberControlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriberControlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubscriberControlPortType
     */
    @WebEndpoint(name = "SubscriberControlPort")
    public SubscriberControlPortType getSubscriberControlPort() {
        return super.getPort(new QName("http://www.bercut.com/specs/aoi/tele2/SubscriberControlBpel", "SubscriberControlPort"), SubscriberControlPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriberControlPortType
     */
    @WebEndpoint(name = "SubscriberControlPort")
    public SubscriberControlPortType getSubscriberControlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bercut.com/specs/aoi/tele2/SubscriberControlBpel", "SubscriberControlPort"), SubscriberControlPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBSCRIBERCONTROLSERVICE_EXCEPTION!= null) {
            throw SUBSCRIBERCONTROLSERVICE_EXCEPTION;
        }
        return SUBSCRIBERCONTROLSERVICE_WSDL_LOCATION;
    }

}
