
package com.bercut.specs.aoi.tele2.subscribercontrolbpel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubscriberControlPortType", targetNamespace = "http://www.bercut.com/specs/aoi/tele2/SubscriberControlBpel")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SubscriberControlPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.bercut.specs.aoi.tele2.subscribercontrolbpel.SubscriberControlResponse
     */
    @WebMethod(operationName = "GetSubsInfoMSISDN")
    @WebResult(name = "SubscriberControlResponse", targetNamespace = "http://www.bercut.com/specs/aoi/tele2/SubscriberControlBpel", partName = "parameters")
    public SubscriberControlResponse getSubsInfoMSISDN(
        @WebParam(name = "GetSubsInfoMSISDNRequest", targetNamespace = "http://www.bercut.com/specs/aoi/tele2/SubscriberControlBpel", partName = "parameters")
        GetSubsInfoMSISDNRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bercut.specs.aoi.tele2.subscribercontrolbpel.SubscriberControlResponse
     */
    @WebMethod(operationName = "GetSubsInfoSubsId")
    @WebResult(name = "SubscriberControlResponse", targetNamespace = "http://www.bercut.com/specs/aoi/tele2/SubscriberControlBpel", partName = "parameters")
    public SubscriberControlResponse getSubsInfoSubsId(
        @WebParam(name = "GetSubsInfoSubsIdRequest", targetNamespace = "http://www.bercut.com/specs/aoi/tele2/SubscriberControlBpel", partName = "parameters")
        GetSubsInfoSubsIdRequest parameters);

}
